### ISSUE TITLE
The css url property doesn't appear to work

### ISSUE THREAD

**Issue by shaunhillier** [ArnoldSmith86/virtualtabletop#150] opened 2021-01-23 16:55 UTC
I tried adding a simple .css file to the page using an encoded JSON as described in the wiki but couldn't get it to work.

**Comment by robartsd** [comment] 2021-01-23 17:21
Browser developer tools show that the link is added to the html and that the resource is loaded. Current theory is that the server hosting the css must provide an appropriate MIME type or browsers don't accept the file as a css stylesheet. We can't change the behavior of external servers. I don't know if there is anything we can do to suggest browsers ignore the MIME type and read the file as text/css. I don't think we want to fetch the file and serve it up or inject its contents into a style element.

**Comment by RaphaelAlvez** [comment] 2021-01-23 17:42
@robartsd So is this plan dead from a technical point of view?

**Comment by robartsd** [comment] 2021-01-23 18:01
> @robartsd So is this plan dead from a technical point of view?

If the theory is correct, using the URL parameter to apply a stylesheet will only work if you can host the file on a server that will serve it up as text/css. I haven't done any testing other than to check out links that are reported as not working in Discord. As I understand it, the feature is intended primarily for providing a way to style a room that is placed in an iframe; most of those users will be able to host a stylesheet as text/css and should not have an issue.

As a game designer I want to be able to set a stylesheet for my game - that link should be stored in the variant's "_meta" property an should be able to be hosted properly in ../assets/. Requiring a URL parameter to get the game styles as intended would not be a good solution.

**Comment by robartsd** [comment] 2021-01-24 00:38
Found one reference to a MIME type issue causing such a problem, but it seems that it only emerged as a problem when non-ASCII characters are in the CSS file. [https://stackoverflow.com/questions/16513530/why-is-my-css-style-not-being-applied#answer-44696080](url)

**Comment by shaunhillier** [comment] 2021-01-25 09:09
So is it possible to add a style sheet at the moment to the "_meta" property, or would I need to raise a separate enhancement. I agree that the URL properties wasn't a great long term solution for mandatory game styles.

**Comment by robartsd** [comment] 2021-01-25 15:05
> So is it possible to add a style sheet at the moment to the "_meta" property, or would I need to raise a separate enhancement. I agree that the URL properties wasn't a great long term solution for mandatory game styles.

There is currently not any method for adding a game stylesheet.

**Comment by robartsd** [comment] 2022-02-10 17:00
Widget stylesheets provide just about all the functionality that game stylesheets could provide. External room stylesheets probably work, but are more difficult to use that expected (MIME type sensitivity prevents hosting the stylesheet on cloud storage that is not intended for web hosting).

Should we close this issue?

**Comment by 96LawDawg** [comment] 2022-08-05 16:18
I think the drastic changes made to css a few months ago have addressed this. Should be closed

**Comment by 96LawDawg** [comment] 2022-08-05 16:21
Closed

**Closed by 96LawDawg** 2022-08-05 16:21 UTC
Labels: bug
