### ISSUE TITLE
Copy/paste in JSON editor

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#404] opened 2021-04-20 13:01 UTC
Sometimes (unfortunately I can't quantify exactly when) if I copy a block of functions in the JSON editor and then try to past them back in somewhere else, they just end up in some random location in the file, usually near the top somewhere. It's a real pain to undo. (I'm on a Mac, so I have the Command-C and Command-V keys that don't interfere, I think, with the keys for the editor).

**Comment by ArnoldSmith86** [comment] 2021-04-20 13:55
Possibly duplicate of #378?

**Comment by rogerl50** [comment] 2021-04-20 13:56
Could be.

**Comment by ArnoldSmith86** [comment] 2021-05-13 22:09
PR-SERVER-BOT: You can play around with it here: http://212.47.248.129:3404/pr-test (or any other room on that server)

**Comment by 96LawDawg** [comment] 2021-12-06 03:32
Resolved by #356 or #616 or one of the many other changes to the JSON editor.

**Closed by 96LawDawg** 2021-12-06 03:32 UTC
Labels: bug, JSON editor
