### ISSUE TITLE
JSON editor does not have INPUT function

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#505] opened 2021-05-30 01:27 UTC
I've never tried to use it until now, so I just noticed.  All the other functions are there except for INPUT.

**Comment by ArnoldSmith86** [comment] 2021-06-01 21:31
Duplicate of #500.

**Comment by 96LawDawg** [comment] 2021-06-01 21:32
How did I not notice that??  It was literally the same day.

**Closed by ArnoldSmith86** 2021-06-01 21:31 UTC
