### ISSUE TITLE
Setting childrenPerOwner on a holder prevents piles > 2 from forming.

### ISSUE THREAD

**Issue by bjalder26** [ArnoldSmith86/virtualtabletop#494] opened 2021-05-27 17:02 UTC
I can't imagine this is a common occurrence, but while doing some random testing for another PR I found that changing childrenPerOwner to true limited piles formed in that holder to 2.  That is not to say a larger pile can't be moved to the holder.  However, if you drop cards in the holder one by one, they will form piles of 2.  So dropping in 52 cards would form 26 piles of 2.

I put an example in the upper right-hand corner of this room.
https://virtualtabletop.io/rgp2

**Comment by robartsd** [comment] 2021-05-27 17:15
Duplicate of #114. #435 is an attempt to solve, but I haven't set up a local server to do the TestCafe update (not sure why it would be needed).

**Closed by robartsd** 2021-05-27 17:15 UTC
