### ISSUE TITLE
copy-pasting is still broken in JSON editor

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#378] opened 2021-04-11 20:42 UTC
For example: click on macro, do CTRL A, C, V and the contents change (they shouldn't).

**Comment by ArnoldSmith86** [comment] 2021-06-29 14:37
Hmm, I can't reproduce this right now. If you encounter a copy/paste problem, please try to make it reproducible and report it.

**Comment by ArnoldSmith86** [comment] 2021-07-08 15:17
It happened again for me in Firefox 84 on Linux. Just CTRL-clicking a widget and doing CTRL A, C, V only replaces the first line by the pasted content instead of everything.

`getSelection().focusOffset` returns `1` (but clearly more than one character is selected):

![image](https://user-images.githubusercontent.com/73538315/124947285-fbe2ad00-e00f-11eb-9367-e40f9244a470.png)

`$('#jeText').textContent` still contains the entire previous text.

It works correctly if I select everything manually by dragging the clicked cursor. `Select All` in the context menu also breaks it.

**Comment by ArnoldSmith86** [comment] 2021-07-08 15:25
Can somebody test this in a different Firefox?

**Comment by rogerl50** [comment] 2021-07-08 15:50
Same behavior in FF 89.0.2 on MacOS Catalina. However, if I CMD-A (like Ctrl-A) CMD-C, then go to a different widget and just CMD-V, the entire buffer gets pasted into the new widget (and of course the old text from that widget is still there.) So the problem is in the deletion of the selected material, not in the paste itself, I think.

**Comment by 96LawDawg** [comment] 2021-07-08 16:48
Same for me in FF 89.0.2 Windows.  No problems in Edge or Chrome.  I agree with @rogerl50's assessment of what seems to be happening.

**Comment by 96LawDawg** [comment] 2021-12-06 03:22
Resolved by #356 or #616 or one of the many other changes to the JSON editor.

**Closed by 96LawDawg** 2021-12-06 03:22 UTC
Labels: bug, JSON editor
