### ISSUE TITLE
wrong selection when adding a property to cards

### ISSUE THREAD

**Issue by ArnoldSmith86** [ArnoldSmith86/virtualtabletop#613] opened 2021-06-28 09:00 UTC
If the added property is after the virtual properties `cardDefaults` and `cardType`, the selection is too far to the top. So apparently those virtual properties are added _after_ the calculation of the selection.

This is how it looked when I clicked the `fixedZ` button: 
![image](https://user-images.githubusercontent.com/73538315/123609553-0925bd80-d800-11eb-9b96-0db089f3c33c.png)

**Comment by bjalder26** [comment] 2021-06-28 15:33
I think this is because it is alphabetizing the properties.  It is also kind of a problem finding a property when a property name lies between a changeRoutine and a clickRoutine, or between two different changeRoutines.  Debug is a classic example, which will lie after the clickRoutine, but before most propertyChangeRoutines.

Maybe long properties like anything ending in Routine, or starting with card should be pushed to the end.

**Comment by ArnoldSmith86** [comment] 2021-06-29 14:42
Can anyone reproduce this?

**Comment by bjalder26** [comment] 2021-07-26 19:38
> Can anyone reproduce this?

I cannot.  Perhaps it was a fixedZ issue, or something merged fixed it.

**Comment by rogerl50** [comment] 2022-05-26 16:44
Should this issue be closed? It appears to be unreproducible.

**Comment by rogerl50** [comment] 2022-07-28 18:31
I will close this as unreproducible soonish unless someone objects.

**Comment by 96LawDawg** [comment] 2022-07-28 18:42
First time I messed with this.  Could not reproduce the problem.  Recommend closing.

**Comment by rogerl50** [comment] 2022-08-01 18:53
Closed as unreproducible

**Closed by rogerl50** 2022-08-01 18:53 UTC
Labels: bug, JSON editor
