### ISSUE TITLE
CALL should have a count parameter

### ISSUE THREAD

**Issue by rogerl50** [ArnoldSmith86/virtualtabletop#504] opened 2021-05-29 13:38 UTC
It would be useful, particularly since there is no iteration construct yet, if CALL had a count parameter, so that it could be invoked (say) for each element of a list, something like: 
```
CALL count = list length
routine:
 pop element off list
  do whatever you do
```

**Comment by 96LawDawg** [comment] 2021-05-29 14:07
Duplicate of #492

**Closed by 96LawDawg** 2021-05-29 14:07 UTC
