### ISSUE TITLE
Maximum size of a pile is only 2 when in a hand 

### ISSUE THREAD

**Issue by ThePropagandaPanda** [ArnoldSmith86/virtualtabletop#114] opened 2021-01-15 00:41 UTC
If you set "stackOffset" to 0 in a hand, cards will obviously be piled upon each other like in a common holder. However, the maximum size of a pile seems to be 2 once it is in a hand. If you pull in more cards, they will still stack on each other visually, but a new pile will be created. So let's say, you have 6 cards on top of each other - it won't be a pile of 6, but three piles of 2 lying on each other.

This interaction with  "childrenPerOwner" is probably not surprising (not sure if it is intended, though?!). But in some games, it would come in handy if piling within a hand was possible. For example, in games where there are different currencies (let's say blue, red, green), and players are taking money from a face-down deck each turn; instead of having all individual money cards in your hand, it'd be more convenient if all blue (red, green) money cards were just stacked upon each other in three piles (= three hands)
![a](https://user-images.githubusercontent.com/77340016/104665876-c26d5c80-56d2-11eb-8bbe-554898b91d91.gif)
.

**Comment by robartsd** [comment] 2021-01-15 03:58
Also, other players can see and interact with the pile (but not the cards in the pile). I think the problem is the pile isn't owned by the player even though both cards in the pile are.

**Comment by ArnoldSmith86** [comment] 2021-01-15 09:02
Huh. Thanks for reporting.

**Comment by bjalder26** [comment] 2021-05-27 18:18
Putting this enterRoutine on the holder appears to be an effective workaround until PR #435 is merged.

 "enterRoutine": [
    {
      "func": "SELECT",
      "type": "pile",
      "property": "parent",
      "value": "${thisID}",
    },
    {
      "func": "SET",
      "property": "owner",
      "value": "${playerName}"
    }
  ]

**Comment by robartsd** [comment] 2021-05-27 18:54
> Putting this enterRoutine and onLeave on the holder appears be an effective workaround until PR #435 is merged.

`enterRoutine` workaround is a good idea. I don't think the `onLeave` part is needed, holders with `childrenPerOwner` do that automatically, but maybe the pile messes with it?

**Comment by bjalder26** [comment] 2021-05-27 19:22
Yes, the pile does that automatically, but the cards do not and I found they were still not visible IF dragged out by the handle of the pile.  Otherwise they were fine.

**Closed** 2021-06-14 06:24 UTC
Labels: bug
