### ISSUE TITLE
Duplicating a widget should duplicate everything children excluding cards.

### ISSUE THREAD

**Issue by RaphaelAlvez** [ArnoldSmith86/virtualtabletop#73] opened 2021-01-10 14:37 UTC
I see parents and children as only one widget.
This would allow to easily duplicate a counter, pile with deck and recall button or more complex setups made by the game designers

Cards can easily be added in the deck menu and probably shouldn't be affected by this.

**Comment by UltimateGeek** [comment] 2021-01-10 14:49
Duplicate of #16 ?

**Comment by UltimateGeek** [comment] 2021-01-10 14:52
What's the downside to duplicating the cards if they exist in pile in a holder the contains their deck?

**Closed** 2021-01-10 15:10 UTC
Labels: duplicate

**Comment by RaphaelAlvez** [comment] 2021-01-10 15:23
This issue is duplicated. I added my response in you original issue. #16
