### ISSUE TITLE
Multiple buttons and debug do not work well together

### ISSUE THREAD

**Issue by 96LawDawg** [ArnoldSmith86/virtualtabletop#336] opened 2021-04-03 00:53 UTC
If debug is set to true in Button A, and Button A clicks on Button B which also has the debug property set, it is not possible to see the output of both debugs.

**Comment by ArnoldSmith86** [comment] 2021-04-16 21:04
Duplicate of #388.

**Closed by ArnoldSmith86** 2021-04-16 21:04 UTC
Labels: routine operations
