### ISSUE TITLE
${PROPERTY something} doesn't work in handleCSS

### ISSUE THREAD

**Issue by Ingegneus** [ArnoldSmith86/virtualtabletop#1621] opened 2023-02-13 21:27 UTC
what the title says. it would be nice for consistency and ease of use, to be able to do the same stuff you can do in the normal css

**Comment by 96LawDawg** [comment] 2023-02-13 21:34
It would be a property of the pile, right?  Not of the cards that make up the pile?

**Comment by Ingegneus** [comment] 2023-02-13 21:44
yes

**Comment by ArnoldSmith86** [comment] 2023-02-13 21:45
You can use `css` to style `.handle` and there you can use properties. But yeah, some day...

**Comment by robartsd** [comment] 2023-02-13 23:52
Duplicate of #1304 

Use the property in `css`.
```json
"css": {
  " .handle": {
    "styleName": "${PROPERTY something}"
  }
}
```
OR
```json
"css": "--something: ${PROPERTY something}",
"handleCSS": "styleName: var(--something)"
```

> But yeah, some day...
Maybe ... probabaly not.

**Closed by robartsd** 2023-02-13 23:52 UTC
