### ISSUE TITLE
Bunch of cards in holder disappeared while multiple people manipulated

### ISSUE THREAD

**Issue by AlanDeSmet** [ArnoldSmith86/virtualtabletop#753] opened 2021-09-17 03:26 UTC
We were playing a game in https://virtualtabletop.io/bvct-thursday . Several people were manipulating the holder `tavern-holder` (Below the "Tavern" label). I can't be sure exactly what happened, but suddenly a bunch of cards in the holder, maybe 10, holder disappeared, leaving 3. As people moved the remaining cards around trying to figure out where they were, another disappeared, leaving two.

I'll leave the window with the room open in hopes it won't disappear in case there is any useful information present in it.

**Comment by rogerl50** [comment] 2021-09-17 11:49
I had a similar thing happen in a different room a while back. There were 17 cards whose parent was a pile that did not exist. I created the pile (in the room you posted) and the cards reappeared. So that room is now usable, but of course that does not explain what happened in the first place. When this happened to me, there was a white screen flash, indicating a client crash for some (perhaps related, perhaps unrelated) reason, and afterwards the card was gone. Did you see something similar?

**Comment by AlanDeSmet** [comment] 2021-09-17 14:11
I totally forgot that, sorry! Yes, everyone involved commented that the page reloaded. I believe most people saw it happen at about the same time that the cards disappeared. I believe it reloaded for me a minute or so later, but after the cards had disappeared.

**Comment by bjalder26** [comment] 2021-09-17 18:18
A pile got deleted somehow.  It was a pile with an id of "7an9".  When I made a pile with the same id (in another room) 17 cards appeared on top of it.
![image](https://user-images.githubusercontent.com/78324099/133835450-a77d7ded-e2c5-4162-b663-26cd59f45fa4.png)

**Comment by bjalder26** [comment] 2021-09-24 19:23
I'm wondering if the cause of the crash is related to #439.  I figure that a crash occurred right as a pile was deleted.  Since this has happened twice recently I would assume that the crash and the pile being deleted are related rather than just two things that happened at the same time.

Since the pile isn't being deleted because the 2nd to last card was removed, I figure it must be being deleted because a new pile is supposed to be forming.  Thus, I suspect a pile is being dropped onto another pile or a card.

Because that wouldn't normally cause a crash, I am assuming it is causing a crash because the card or pile on the bottom is moving at the time.  If that is the cause, then I believe we can fix it by fixing #439, which I think will be easier after I merge #716, because that will already have a mechanism for tracking when a card is being dragged.

**Comment by 96LawDawg** [comment] 2023-01-15 01:59
I am going to close this.  Various code changes since then seem to have reduced the frequency and no reports like this have been made in a long time.

**Closed by 96LawDawg** 2023-01-15 01:59 UTC
Labels: bug, pile related
